// lib/services/calendar_service.dart

import 'package:device_calendar/device_calendar.dart';
import 'package:flutter/foundation.dart';
import '../data/database.dart';

class CalendarExportResult {
  final bool success;
  final int eventsAdded;
  final String? error;

  const CalendarExportResult({
    required this.success,
    this.eventsAdded = 0,
    this.error,
  });
}

class CalendarService {
  final DeviceCalendarPlugin _plugin = DeviceCalendarPlugin();

  /// Request calendar permission and return whether granted
  Future<bool> requestPermission() async {
    var perms = await _plugin.hasPermissions();
    if (perms.data != true) {
      perms = await _plugin.requestPermissions();
    }
    debugPrint('[Calendar] Permission: ${perms.data}');
    return perms.data == true;
  }

  /// Get available calendars for the user to pick
  Future<List<Calendar>> getCalendars() async {
    final result = await _plugin.retrieveCalendars();
    final calendars = result.data ?? [];
    // Filter to writable calendars
    return calendars.where((c) => c.isReadOnly != true).cast<Calendar>().toList();
  }

  /// Export plan days to a specific calendar
  Future<CalendarExportResult> exportPlan({
    required String calendarId,
    required List<PlanDay> days,
    required DateTime planStartDate,
  }) async {
    debugPrint('[Calendar] Exporting ${days.length} days to calendar $calendarId');

    try {
      int added = 0;

      for (final day in days) {
        if (day.sessionType == 'rest') continue;

        // Calculate the actual date for this training day
        // week 1, dayOfWeek 0 (Mon) = planStartDate adjusted to Monday of that week
        final startOfWeek = _mondayOfWeek(planStartDate, day.week);
        final sessionDate = startOfWeek.add(Duration(days: day.dayOfWeek));

        // Create a morning event (7:00 AM, duration based on estimated time)
        final start = TZDateTime.local(
          sessionDate.year,
          sessionDate.month,
          sessionDate.day,
          7,
          0,
        );

        final durationMins = _estimateDuration(day);
        final end = start.add(Duration(minutes: durationMins));

        final event = Event(
          calendarId,
          title: '${_sessionEmoji(day.sessionType)} ${day.label}',
          description: _buildDescription(day),
          start: start,
          end: end,
        );

        final result = await _plugin.createOrUpdateEvent(event);
        if (result?.isSuccess == true) {
          added++;
        } else {
          debugPrint('[Calendar] Failed to add event: ${result?.errors}');
        }
      }

      debugPrint('[Calendar] Added $added events');
      return CalendarExportResult(success: true, eventsAdded: added);
    } catch (e) {
      debugPrint('[Calendar] Export error: $e');
      return CalendarExportResult(success: false, error: e.toString());
    }
  }

  /// Get the Monday of a given training week relative to plan start
  DateTime _mondayOfWeek(DateTime planStart, int week) {
    // Adjust planStart to its Monday
    final daysFromMonday = planStart.weekday - 1; // Monday = 1
    final monday = planStart.subtract(Duration(days: daysFromMonday));
    return monday.add(Duration(days: (week - 1) * 7));
  }

  /// Estimate session duration in minutes based on distance and pace
  int _estimateDuration(PlanDay day) {
    if (day.distanceKm <= 0) return 30;

    // Parse pace string like "5:30" to seconds per km
    final parts = day.targetPace.split(':');
    if (parts.length == 2) {
      final mins = int.tryParse(parts[0]) ?? 5;
      final secs = int.tryParse(parts[1]) ?? 0;
      final secsPerKm = mins * 60 + secs;
      final totalSecs = secsPerKm * day.distanceKm;
      // Add 10 min for warmup/cooldown
      return (totalSecs / 60).ceil() + 10;
    }

    // Fallback: 6 min/km
    return (day.distanceKm * 6).ceil() + 10;
  }

  String _sessionEmoji(String type) {
    return switch (type) {
      'easy' => '\u{1F7E2}',    // green circle
      'tempo' => '\u{1F7E0}',   // orange circle
      'long' => '\u{1F7E3}',    // purple circle
      'interval' => '\u{1F535}', // blue circle
      _ => '\u{26AA}',          // white circle
    };
  }

  String _buildDescription(PlanDay day) {
    final lines = <String>[];
    lines.add('Type: ${day.sessionType.toUpperCase()}');
    if (day.distanceKm > 0) lines.add('Distance: ${day.distanceKm} km');
    if (day.targetPace != '\u2014') lines.add('Target Pace: ${day.targetPace}/km');
    if (day.effortZone > 0) lines.add('Effort Zone: ${day.effortZone}/5');
    if (day.notes != null && day.notes!.isNotEmpty) lines.add('\n${day.notes}');
    lines.add('\nGenerated by VO2.ai');
    return lines.join('\n');
  }
}
